--- #YAML:1.0
name:                Querylet-Output-Excel-XLS
version:             0.131
abstract:            output querylet results to an Excel file
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Querylet::Output:              0.24
    Querylet::Query:               0.28
    Spreadsheet::WriteExcel:       2.04
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo SIGNES <rjbs@cpan.org>
